#!/usr/bin/env bash
# Generate terraform/backend.hcl (gitignored) from .env. Nothing naming the account is ever
# hand-edited or committed.
set -euo pipefail
. "$(dirname "$0")/common.sh"

OUT="$REPO_ROOT/terraform/backend.hcl"

cat > "$OUT" <<HCL
# GENERATED by scripts/write-backend.sh - do not commit, do not edit by hand.
bucket       = "$(state_bucket)"
# Historical name. The resources were first applied under it, and renaming the key would
# mean copying the state object in S3 for purely cosmetic gain.
key          = "platform/terraform.tfstate"
region       = "$AWS_REGION"
profile      = "$AWS_PROFILE"
encrypt      = true
use_lockfile = true
HCL
echo "wrote $OUT"
