#!/usr/bin/env bash
# Generate terraform/backend.hcl (gitignored) from .env. Nothing naming the account is ever
# hand-edited or committed.
set -euo pipefail
. "$(dirname "$0")/common.sh"

ROOT_NAME="${1:-platform}"
# One file per root. A shared backend.hcl is a trap: it is rewritten on every init,
# so a manual `terraform init -backend-config=...` can point one root at the other
# root's state key.
OUT="$REPO_ROOT/terraform/$ROOT_NAME/backend.hcl"

cat > "$OUT" <<HCL
# GENERATED by scripts/write-backend.sh - do not commit, do not edit by hand.
bucket       = "$(state_bucket)"
key          = "${ROOT_NAME}/terraform.tfstate"
region       = "$AWS_REGION"
profile      = "$AWS_PROFILE"
encrypt      = true
use_lockfile = true
HCL
echo "wrote $OUT for root '$ROOT_NAME'"
