#!/usr/bin/env bash
# Generate terraform/backend.hcl (gitignored) from .env. Nothing naming the account is ever
# hand-edited or committed.
set -euo pipefail
. "$(dirname "$0")/common.sh"

OUT="$REPO_ROOT/terraform/backend.hcl"
ROOT_NAME="${1:-platform}"

cat > "$OUT" <<HCL
# GENERATED by scripts/write-backend.sh - do not commit, do not edit by hand.
bucket       = "$(state_bucket)"
key          = "${ROOT_NAME}/terraform.tfstate"
region       = "$AWS_REGION"
profile      = "$AWS_PROFILE"
encrypt      = true
use_lockfile = true
HCL
echo "wrote $OUT for root '$ROOT_NAME'"
